openapi: 3.0.2
info:
  title: Edge Normalization Service
  description: 'A REST service for resolving predicates into Biolink model compliant predicates.'
  version: '1.0.0'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
paths:
  /resolve_predicate:
    get:
      tags:
        - redis
      summary: 'Resolve predicate(s) into Biolink model compliant counterpart(s).'
      description: 'Get Biolink model compliant predicate(s) using the passed predicate(s).'
      parameters:
        - in: query
          name: predicate
          schema:
            type: array
            items:
              type: string
            example:
              - SEMMEDDB:DISRUPTS
      responses:
        '200':
          description: Results
          content:
            application/json:
              schema:
                type: object
                example:
                  "SEMMEDDB:DISRUPTS":
                    "identifier": "SEMMEDDB:DISRUPTS"
                    "label": "disrupts"