openapi: 3.0.2
info:
  title: Edge Normalization Service
  description: 'A REST service for resolving predicates into Biolink model compliant predicates.'
  version: '1.0.0'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
paths:
  /resolve_predicate:
    get:
      tags:
        - redis
      summary: 'Resolve predicate CURIE(s) into Biolink model compliant counterpart(s), first checking the BioLink model for
      exact matches of a CURIE.  If the CURIE is from the Relation Ontology, the service will check its superproperties until
       an exact match is found.'
      description: 'Get Biolink model compliant predicate(s) using the passed predicate(s).'
      parameters:
        - in: query
          name: predicate
          schema:
            type: array
            items:
              type: string
            example:
              - SEMMEDDB:CAUSES
              - RO:0000052
        - in: query
          name: version
          schema:
            type: string
            example: "latest"
      responses:
        '200':
          description: Results
          content:
            application/json:
              schema:
                type: object
                example:
                  "SEMMEDDB:CAUSES":
                    "identifier": "RO:0002410"
                    "label": "causes"
                  "RO:0000052":
                    "identifier": "SEMMEDDB:AFFECTS"
                    "label": "affects"