apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-normalization-deployment
  labels:
    service: edge-normalization
    app: edge-normalization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-normalization
  template:
    metadata:
      labels:
        app: edge-normalization
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: edge-normalization
        image: renciorg/edgenormalization:latest
        ports:
          - containerPort: 8145
            name: http
        env:
          - name: BL_HOST
            value: 'https://bl-lookup-sri.renci.org'
      restartPolicy: Always