apiVersion: v1
kind: Service
metadata:
  name: edge-normalization
spec:
  type: LoadBalancer
  loadBalancerIP: nnn.nn.nn.nnn # replace with real IP
  selector:
    app: edge-normalization
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8145